name: Publish package on NPM
on:
  paths:
    - 'packages/node/**.js'
  push:
    branches:
      - master

defaults:
  run:
    working-directory: packages/node

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12.x'
        registry-url: 'https://registry.npmjs.org'
    - run: npm install
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
